# Generated by Django 4.0.6 on 2022-07-16 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rwitter', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rweets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
